#!/bin/sh

# wifi-monitor v7.0
# Bruno "GNUser" Dantas GPLv3

# user variables:
iface=wlan0
icon=/opt/scripts/media/wifi.png

main()
{
	while true; do
		if curl --silent --max-time 10 --head http://duckduckgo.com >/dev/null; then
			ssid="$(iwconfig $iface | grep ESSID | awk -F\" '{print $2}')"
			icon_add "$icon" "$ssid"
		else
			icon_remove "$icon"
		fi
		sleep 10
	done
}

icon_add()
{
	if pgrep -f "mktrayicon.*$1" >/dev/null; then
		return
	else
		mktrayicon -i "$1" -t "$2" &
	fi
}

icon_remove()
{
	if pgrep -f "mktrayicon.*$1" >/dev/null; then
		pkill -f "mktrayicon.*$1"
	else
		return
	fi
}

main
