#!/bin/sh

# wifi-monitor v4.0
# Bruno "GNUser" Dantas GPLv3

# user variables:
iface=wlan0
icon=/path/to/wifi.png
icon_location=systray # options are systray or wbar

main()
{
	while true; do
		if curl --silent --head http://duckduckgo.com >/dev/null; then
			ssid="$(iwconfig $iface | grep ESSID | awk -F\" '{print $2}')"
			icon_add
		else
			icon_remove
		fi
		sleep 10
	done
}

icon_add()
{
	if [ "$icon_location" = "systray" ]; then
		[ -e $yad_pid_file ] && return
		yad --notification --image="$icon" --icon-size=24 --text="$ssid" --command=true &
		echo $! > $yad_pid_file
	elif [ "$icon_location" = "wbar" ]; then
		grep -q "$icon" "$wbar_config_file" && return
		printf "i: $icon\nt: $ssid\nc: true\n" >> $wbar_config_file
		pkill wbar && wbar >/dev/null 2>&1 &
	fi
}

icon_remove()
{
	if [ "$icon_location" = "systray" ]; then
		[ -e $yad_pid_file ] || return
		kill $(cat $yad_pid_file) && rm $yad_pid_file
	elif [ "$icon_location" = "wbar" ]; then
		grep -q "$icon" "$wbar_config_file" || return
		sed -i "\|$icon|,+2 d" $wbar_config_file
		pkill wbar && wbar >/dev/null 2>&1 &
	fi
}

# internal variables
yad_pid_file=/tmp/online-icon-pid
wbar_config_file=$HOME/.wbar

main
